### ISSUE TITLE
Add validation to magnet link resolver

### ISSUE THREAD

**Issue by merlinnusr** [orcproject/orc#111]
orc      9.1.0
protocol 4.0.0

### Expected Behavior

An error window saying "You need paste at least one URL"

### Actual Behavior

Crash 

### Steps to Reproduce

I have a:

 Linux moe 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

1. Start orc
2. [Click in the plus bottom and click in import (without any url)](https://imgur.com/d8vweCt)
3. [Crash](https://imgur.com/JoAsN9l)

**Comment by bookchin** [comment]
https://github.com/orcproject/orc/pull/110/commits/6537fa5eff15b2ecd9cdcb745bc905b5748349a8
