### ISSUE TITLE
Windows client won't start

### ISSUE THREAD

**Issue by ildoc** [orcproject/orc#115]
### Package Version

```
orc      9.2.2
node     v8.6.0
```

### Expected Behavior

Windows client starts with no issues

### Actual Behavior

A popup appears:

![](https://i.imgur.com/c2eO9Oc.png)

### Steps to Reproduce

Perform a clean windows installation and launch Orc

**Comment by bookchin** [comment]
Seems related to the second part of #109. Can you follow the manual install guide and run from source and paste the console output here?

https://orcproject.github.io/orc/tutorial-install.html

In the meantime, I'll open a ticket for writing a log file when ORC is run from the GUI so these issues are easier to report and debug.

**Comment by bookchin** [comment]
#116

**Comment by quoidautre** [comment]
Hi,
I have this issue too. When I launch the .exe file, the error popup appears a long time after : 2 or 3 minutes !

And, if I wait again, there's that : 
![Image of Yaktocat](https://framapic.org/vJJD47jbAXF8/qVkNG451tXDN.jpg)

**Comment by bookchin** [comment]
Update, I managed to reproduce this issue after a clean install (also removing `$HOME/.config/orc`) and this is triggered during first time setup and generation of keys. Working on a fix now and will publish a new release this week. :)

**Comment by bookchin** [comment]
Also, can confirm that this is only an issue with the GUI.

**Comment by quoidautre** [comment]
Thanks :)

Fabrice

**Comment by quoidautre** [comment]
I just installed the 9.3.0, and same error :(. It crash !
