### ISSUE TITLE
BufferSize must be the product of shardLength and totalShards

### ISSUE THREAD

**Issue by Th3Van** [orcproject/orc#23]
### Package Version

Replace the value below using the output from `orc --version`.

```
orc      0.0.0
protocol 2.0.0
```

Replace the value below using the output from `node --version`.

```
v6.11.1337
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in back ticks.

Downloading a test 100MB file, seems to be ending with a error :
```
curl http://127.0.0.1:4445/d55e81af-66cc-4082-97fa-8d6af1145e9f > 100MB-file-download.test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    61    0    61    0     0      0      0 --:--:--  0:01:47 --:--:--    16

root@server007:~/orc# cat 100MB-file-download.test 
bufferSize must be the product of shardLength and totalShards
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

**1.** openssl rand 100000000 > 100MB-File.test
**2.** curl -F "file=@100MB-File.test;filename=100MB-File.test" http://127.0.0.1:4445 | jq | grep '"id"'
**3.** curl http://127.0.0.1:4445/d55e81af-66cc-4082-97fa-8d6af1145e9f > 100MB-file-download.tes**t**

**Comment by bookchin** [comment]
I think this is fixed in the latest. Can you confirm with new upload?

**Comment by Th3Van** [comment]
OK, updated to beta4, but same result : 

**Upload :**
```
root@server028:~# rm 100MB-File.test
root@server028:~# openssl rand 100000000 > 100MB-File.test
root@server028:~# curl -F "file=@100MB-File.test;filename=100MB-File.test" http://127.0.0.1:4445 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.3M    0 20302  100 95.3M     81   391k  0:04:09  0:04:09 --:--:--     0
  "id": "9d475e0a-905b-4a1d-bee5-261ffbf4d7d1",
```

**Download :**
```
root@server028:~# curl http://127.0.0.1:4445/9d475e0a-905b-4a1d-bee5-261ffbf4d7d1 > 100MB-file-download.test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    61    0    61    0     0      0      0 --:--:--  0:03:16 --:--:--    15

root@server028:~# ls -l 100MB-file-download.test
-rw-r--r-- 1 root root 61 Jul 26 18:33 100MB-file-download.test

root@server028:~# cat 100MB-file-download.test  
bufferSize must be the product of shardLength and totalShards
```

```
root@server028:~# orc --version
  orc      7.0.1-beta4
  protocol 2.0.0

root@server028:~# node --version
v6.11.0
```
A 50MB file seems to be working flawlessly.
More logging while downloading?

**Comment by bookchin** [comment]
Yeah, will add more debug logging as see if we can track it down.

**Comment by bookchin** [comment]
Okay, I can consistently reproduce this, so I'm going to work on fixing it as I add logging.

**Comment by bookchin** [comment]
I can confirm it's a floating point math problem.

**Comment by bookchin** [comment]
Fixed in https://github.com/bookchin/orc/commit/ed60ecd51d7cadb1c73300d1ae01538c759a095e and will be merged this week :)
