### ISSUE TITLE
IMP-12

### ISSUE THREAD

**Issue by bookchin** [orcproject/orc#4]
Implement https://github.com/orcproject/imps/blob/master/imp-0012.md as an experiment.

**Comment by bookchin** [comment]
Part of work on local renter bridge and farmer profiles

**Comment by nginnever** [comment]
Is there an issue for kicking off these renter/farmer profile specs? Is this for knowing how payments can be done in a decentralized manor i.e. when to reward / penalize? I think these may be hard questions and we would be looking at protocols like Sia and other smart contract like escrow systems, or distributed reputation, or centralization.

- A centralized bridge can simplify all problems by setting a price and becoming the judge/jury but it comes with its own issues of trust, downtime, or human error .

- Blockchain solutions like Sia or Filecoin get a network of computers competing to confirm and escrow transactions / contracts. An important fact here is that trust can be bypassed with bonds and insurance. Mining coins can lead to problems of unstable markets.

- All decentralized systems have potential economy problems that the free market is tasked to solve and sometimes fails as modeling value that works for all nations and financial classes can be a hard general problem. 

I propose a simple non-blockchain solution to start with where individual interaction works similar to the idea you mentioned on call. This protocol is interactive.

Contracts define:
```
- size of storage
- length of storage 
- interval of proofs 
- reward for proofs 
- amount of proofs that can be missed (defining challenge window)
- number of payments that can be missed. (define payment window)
```
For example Alice could have a contract with Bob and Alice tries to cheat Bob into storing the file and not paying then Bob will cancel the contract in the agreed upon payments missed with given time frame and discard the file, or Alice may stop paying Bob in the same way. 

This system will work as long as everyone is dedicated to managing their own trust at all times. Payments and issuance of proofs are perhaps the most cumbersome part of the renter experience (staying online to prove / pay for storage). 

_Perhaps with more work in the future:_

Reputation system:

Maybe a way to build trust in facilitating nodes could work? A reputation system could create a set of nodes that will run `reputation daemon` with a `payment subroutine`. Signed messages between light client renters and reputation nodes could create a web of trust and a system of built interaction trust where nodes are paid a fee to facilitate proofs or are doing it out of altruism (like tor exit nodes, though in this case monetary value is involved incentivizing nodes to misbehave). 

These messages need some channel to coordinate building the trust in nodes for renters and sending the crypto funds for paying the farmers. 

Distributed reputation is a hard problem itself but in the context of file storage it is probably doable.  The question here is where to place the trust with no escrow?

**Comment by bookchin** [comment]
Some notes/thoughts:
  * Provider nodes must deposit X into a new transparent address to be considered for storage
  * Deposit must be maintained in order to continue accepting new contracts
  * Capacity announcements must include the taddr/txid/signature
  * Start adding `fundingDestination` to contracts
  * Audits must be coupled with payments
  * Shards are reaped if no payment has been issued with N blocks
  * Storage is free for N blocks (as in the use case for sharing temporary objects is free)

**Comment by bookchin** [comment]
https://github.com/orcproject/imps/blob/master/imp-0012.md
