### ISSUE TITLE
Integrate Next Generation Onion Services

### ISSUE THREAD

**Issue by bookchin** [orcproject/orc#61]
https://blog.torproject.org/tor-0321-alpha-released-support-next-gen-onion-services-and-kist-scheduler

**Comment by stoically** [comment]
https://trac.torproject.org/projects/tor/ticket/20699

**Comment by bookchin** [comment]
https://trac.torproject.org/projects/tor/wiki/doc/NextGenOnions#Howtosetupyourownprop224service

**Comment by bookchin** [comment]
https://github.com/bookchin/hsv3

**Comment by bookchin** [comment]
Kad Onion plugin is ready for integration with ORC
