### ISSUE TITLE
App doesn't load on Ubuntu 16.04

### ISSUE THREAD

**Issue by stoically** [orcproject/orc#82]
Hi,

### Package Version

Replace the value below using the output from `orcd --version`.

```
  orc      9.0.3
  protocol 3.1.0
```

Replace the value below using the output from `node --version`.

```
v8.7.0
```

uname -a
```
Linux 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 GNU/Linux
```

### Expected Behavior

App should start as expected

#### from source (v9.0.3)
BrowserWindow (stuck)
```
spawning tor client and controller
```

#### /usr/lib/orc/ORC (via .deb)
Alert
```
Uncaught Exception:
Error: EACCES: permission denied, open '/usr/lib/orc/resources/app/node_modules/mongodb-prebuilt/built/bin/.mongodb-prebuilt/mongodb-download/mongodb-linux-x86_64-ubuntu1604-latest.tgz.downloading'
```

Commandline (stuck)
```
~$ /usr/lib/orc/ORC
Completed: 0 % (0mb / 97.1mb
```

BrowserWindow (stuck)
```
starting orc daemon
```

No Errors on Developer Console in both cases. It seems that the from source version hangs when starting granax(). Can't debug with console.log or the actual stdout tho since I have no idea how to get that output out of electron-compile.

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

from source
1. git clone (master=9.0.3)
2. npm install
3. npm link
4. orc

.deb
1. Download and Install .deb
2. Start /usr/lib/orc/ORC

If I can provide more information, please let me know how.

Best regards

**Comment by bookchin** [comment]
I am not able to reproduce this from source, but can reproduce with the deb package. I was able to workaround the issue with the package by running orc with root privileges. I suspect the reason I cannot reproduce from source is that I use NVM which installs everything locally to the user. 

So this must be a permission issue with the built package. Let me know if you can confirm that running orc with sudo works and I will build a new Debian package with the permissions fixed.

**Comment by stoically** [comment]
Yep, running the deb version with sudo works.

I'm using NVM too. As of writing my NVM version was 0.7.0. I've upgraded to the latest 0.33.5 just to make sure, tho it shouldn't make a difference, and it didn't work either. What node version are you using? Any tips how to get the stdout/console.log output from the main electron process so I can debug further?

**Comment by bookchin** [comment]
I have narrowed this down. We use a package called mongodb-prebuilt which installs mongodb as a local node package. When the app runs, it checks to make sure the right mongodb package is installed for the platform and if it isn't, it downloads and unpacks it. 

Problem is that on Linux systems, 2 things happen. I built the package on Debian Sid and on other distros, it wants a different package so it tries to download and unpack a different version in mongo on run, but since installing the deb package writes the files to /usr/lib/orc, when the app tries to write the download it doesn't have permissions. 

This doesn't happen on win/mac because there aren't different versions it wants and so it doesn't try to install anything. I need to refactor this process of bundling mongo anyway, so I will do that today and resolve the issue and package a new release. 

Thanks for the report!

**Comment by bookchin** [comment]
https://github.com/orcproject/orc/pull/84

**Comment by bookchin** [comment]
Release incoming

**Comment by stoically** [comment]
Can confirm that it now works from source. Cool!

Had just one problem, when starting it was stuck at starting mongodm with the error
```
{"name":"a226b051c2a4d435663e2ed1b0b9156cbd15fd47","hostname":"pc","pid":13246,"level":50,"msg":"mongod exited with non-zero code (14), stopping orc","time":"2017-10-21T04:48:09.370Z","v":0}
{"name":"a226b051c2a4d435663e2ed1b0b9156cbd15fd47","hostname":"pc","pid":13246,"level":30,"msg":"exiting, killing mongod","time":"2017-10-21T04:48:09.371Z","v":0}
```
apparently there was a leftover from the deb package:
```
srwx------ 1 root root 0 Oct 20 06:42 /tmp/mongodb-37017.sock=
```
After manually removing the socket, ORC started without problems. Had to manually log the mongod args and start the bundled mongod bin to get that hint tho, since the logging from ORC didn't show the actual error from mongod.

**Comment by stoically** [comment]
Problem still exists in the 9.0.4 deb release on Ubuntu 16.04. I've purged the previous Installation. When running /usr/lib/orc/ORC as user it logs to the console
```
"name":"a226b051c2a4d435663e2ed1b0b9156cbd15fd47","hostname":"pc","pid":22279,"level":50,"msg":"mongod exited with non-zero code (14), stopping orc","time":"2017-10-22T07:42:05.424Z","v":0}
{"name":"a226b051c2a4d435663e2ed1b0b9156cbd15fd47","hostname":"pc","pid":22279,"level":30,"msg":"exiting, killing mongod","time":"2017-10-22T07:42:05.425Z","v":0}
```
and is stuck in the BrowserWindow at
```
exiting, killing mongod
```

Unfortunately I can't debug further since changes I make to the files in resources/app/ don't seem to get picked up by the ORC process.

Running as root works fine.

**Comment by bookchin** [comment]
So strange. Try `rm /tmp/mongodb-37017.sock`?

**Comment by stoically** [comment]
Doesn't make a difference. Same error. After starting it looks like this
```
srwx------ 1 user user 0 Oct 22 18:08 /tmp/mongodb-37017.sock=
```

**Comment by stoically** [comment]
It does work on a fresh Ubuntu 16.04 and 17.10 tho. Seems like system is just borked. Sorry.

**Comment by stoically** [comment]
Works now also on my system after removing ~/.config/orc and reinstalling the deb. :+1:

**Comment by bookchin** [comment]
Ahhh, the `~/.config/orc/data` directory must have been owned by root after running with sudo. Good to hear it's resolved!
