### ISSUE TITLE
Tray Icon doesn't appear on Ubuntu 16.04

### ISSUE THREAD

**Issue by stoically** [orcproject/orc#85]
Hi,

### Package Version

Replace the value below using the output from `orcd --version`.

```
orc      9.0.4 (current HEAD)
protocol 3.1.0
```

Replace the value below using the output from `node --version`.

```
v8.7.0
```

### Expected Behavior

When closing the ORC window a Tray Icon should appear.

### Actual Behavior

Tray Icon does not appear when closing ORC window.

### Steps to Reproduce

1. Make sure libappindicator1 is installed (Needed on Ubuntu, other Apps like Discord or LBRY have it as dependency)
2. git clone
3. npm install
4. npm link
5. orc
6. Close ORC Window

### Note

When creating a fresh project with `electron-forge init` (v4.1.2) and copy over only the Tray logic from the orc  index.js to the forge project index.js (including the .png), it does work. The [Tray Documentation](https://github.com/electron/electron/blob/master/docs/api/tray.md) states that `App indicator will only be shown when it has a context menu.` - tho it didn't make a difference when testing. Putting a context menu into ORC didn't make the Tray Icon appear and not putting Context Menu Code into the forge project still showed the Tray Icon.

Best regards

**Comment by bookchin** [comment]
Which desktop environment is this happening in? Tray icon does appear for me using GNOME 3.x in Ubuntu 16.x (though as referenced in another issue, clicking it restores the window but not the application state).

**Comment by bookchin** [comment]
Also, I do get a tray icon in my primary environment (Debian Sid + i3 + i3status)

**Comment by stoically** [comment]
Default Ubuntu 16.04 Installation - so it's Unity. Gonna test it with 17.10 now, they switched back to GNOME, so it might work there.

**Comment by stoically** [comment]
Well, under Ubuntu 17.10 (Default, which is basically GNOME 3.x with some modifications) no one figured out yet how to place an Icon into the Tray. ORC, Discord, Riot or the plain and simple example with electron-forge or electron itself don't work yet.

**Comment by stoically** [comment]
It seems this problem already exists in 17.04 and still exists in 17.10. Somebody on askubuntu figured out a [solution](https://askubuntu.com/questions/905858/appindicators-not-working-for-electron-applications-skype-for-linux-discord-et) - and the guys over at Wire [implemented](https://github.com/wireapp/wire-desktop/pull/576) it. So when I start e.g. Riot or the simple examples with the `env XDG_CURRENT_DESKTOP=Unity` set, the Tray Icon appears.

**Comment by bookchin** [comment]
Nice sleuthing! Strange that the workaround doesn't work with ORC. Have you tried adding that workaround Wire added and running from source?

**Comment by stoically** [comment]
Yep, I directly set the env var (since the if doesn't work anymore in 17.10 because the env is now set to `ubuntu:GNOME`) first thing in the index.js, both in a fresh electron-forge init (used the same ORC png for new Tray()) and in ORC. Only works for the fresh init tho. Not exactly sure what's the problem here. Also tried to use the latest versions for electron-forge and electron-prebuilt-compile in ORC, but that didn't make a difference either.
