### ISSUE TITLE
App doesn't recover on Windows10 after close when clicking on Tray Icon

### ISSUE THREAD

**Issue by stoically** [orcproject/orc#86]
Hi,

### Package Version

Replace the value below using the output from `orc --version`.
Replace the value below using the output from `node --version`.

.exe from v9.0.3 release

### Expected Behavior

After closing the ORC window and then clicking the Tray Icon, the ORC window should recover and show the File Manager.

### Actual Behavior

After closing and clicking the Tray Icon the Loader is shown and several messages are passing through. It never shows the File Manager again.

### Steps to Reproduce

1. Install .exe
2. Start ORC
3. Close ORC window
4. Click on Tray Icon

### Suggestion

Instead of letting the window actually close when the close X is clicked, just hide it and show it again when the Tray Icon is clicked. E.g. https://stackoverflow.com/a/38980563/4981511 - Discord does the same:
```javascript
    if (process.platform === 'linux' || process.platform === 'win32') {
      setupSystemTray();

      mainWindow.on('close', function (e) {
        if (mainWindow === null) {
          // this means we're quitting
          return;
        }
        webContentsSend('MAIN_WINDOW_BLUR');
        saveWindowConfig(mainWindow);
        setWindowVisible(false);
        e.preventDefault();
      });
    }
```
Seems like an easy fix compared to getting the app state correctly restored. I could provide a PR if needed.

Best regards

**Comment by bookchin** [comment]
Can reproduce on Ubuntu 16 + GNOME 3, window does restore but app state does not.
