### ISSUE TITLE
Context Menu for Tray Icon on Ubuntu 16.04

### ISSUE THREAD

**Issue by stoically** [orcproject/orc#87]
Hi,

the Tray Icon on Ubuntu 16.04 needs a context menu to interact with. The click event on the Icon does not work - as tested and [documented](https://github.com/electron/electron/blob/master/docs/api/tray.md): `When app indicator is used on Linux, the click event is ignored.`

A possible simple solution would be just putting something like
```javascript
  if (process.platform === 'linux') {
    tray.setToolTip('ORC')
    const contextMenu = Menu.buildFromTemplate([
      {label: 'Open ORC', type: 'normal', click: createWindow},
      {label: 'Quit', type: 'normal', click: app.quit}
    ])
    tray.setContextMenu(contextMenu)
  }
```
into the index.js - or `showWindow ` instead of `createWindow` if my suggestion in #86 is taken into consideration. I could provide a PR.

Until #85 is resolved that doesn't really make difference tho.

Thanks again for your work and sorry for the Issue spam.

Best regards

**Comment by bookchin** [comment]
If you have a good idea of how to resolve this, a PR would be fantastic.
