### ISSUE TITLE
Windows Wrapper

### ISSUE THREAD

**Issue by doodlemania2** [orcproject/orc#90]
Seeking Windows wrapper command utility so I can get stdout output running 9.0.4

**Comment by bookchin** [comment]
Looks like this is actually an issue in electron. There is a [workaround here](https://github.com/electron/electron/issues/4552), and i can confirm it works when running from source, however it does not work with the final packaged executable - which is built using squirrel and I have no idea if it's possible to get this working as expected.

Will leave this issue open in the backlog in case anyone discovers a solution and want to open a PR.

**Comment by bookchin** [comment]
https://github.com/orcproject/orc/issues/116
