### ISSUE TITLE
Files don't show up after adding and mostly stay queued

### ISSUE THREAD

**Issue by stoically** [orcproject/orc#95]
Hi,

### Package Version

Replace the value below using the output from `orc --version`.

```
orc      9.1.0
protocol 3.2.0
```

Replace the value below using the output from `node --version`.

```
Bundled (.exe/.deb) and v8.7.0 (git HEAD)
```

### Expected Behavior

Files should immediately show up as "queued" in the File Manager after getting added. Files should switch Status to "finished" - or another status if e.g. something goes wrong - after some time.

### Actual Behavior

Files don't show up in the File Manager after getting added (Edit: they do show up after ~5 minutes - the statement saying "you can wait 20 minutes" was not correct). Restarting after adding shows them immediately. In both cases the status stays "queued" tho. 

### Steps to Reproduce

1. Add File, File doesn't show up, File shows up after ~5 minutes (console has Object with `errStack` saying `Timed out waiting for response`)
2. Restart ORC (before the 5minutes), File shows up immediately but stays "queued"

### Note

Tested with small textfiles (4kb) and version 9.1.0 on Debian9 (GNOME3, git HEAD and .deb) and Ubuntu 16.04 (Unity, git HEAD). On Windows10 (.exe) the file shows up after ~1 minute with status "finished". If I can provide further information please let me know.

Best regards

**Comment by bookchin** [comment]
@mrfancymonocle is working on the UI to provide more feedback around transfer status, error handling/messaging, etc which should help a lot with with this. 

One thing to note is that right now, is that objects in a "queued" state won't resume or retry if they don't complete, they'll just sit in a "failed" state. If you close the application while an object is uploading, it will just sit in a "queued" state. Lots of UX here to work on. 

What doesn't seem right though, is the 20 minute wait time. That indicated something is wrong. You can open the electron developer tools and there should be a state object that gets printed periodically. Open that up and see what's in the `errStack` to see if there is anything there. 

Another way to debug is to run the daemon standalone and use curl to upload a file and watch the daemon logs print what's going on. There is a tutorial on this here: https://orcproject.github.io/orc/tutorial-transfers.html

**Comment by stoically** [comment]
Turns out I exaggerated a bit. The added file always shows up after almost exactly 5 minutes, but it stays in status "queued". The `errStack` on the console shows `Timed out waiting for response`. Same applies for running orcd and uploading files with curl (following the tutorial) - responds with `Timed out waiting for response` after ~5 minutes. Here's the log from orcd for one upload: https://pastebin.com/gQQ1d9fL. Interestingly enough that only happens on Debian9 (.deb) and Ubuntu16.04 (git HEAD) tho, on Windows it now works, the file shows up after ~1 minute with status "finished". (Edited the initial post to reflect that.)

Although from an UX perspective I personally would expect the files to show up immediately, so as a user I know something is happening. Of course I understand that there's a lot to do in the project on all fronts - good to know there's someone working on the GUI already. Just wanted to give my input, hope it doesn't come through as rude.

**Comment by bookchin** [comment]
Not rude at all and didn't take it as such! Interesting that the issue is platform specific for you - I'm wondering if the capacity cache on your Debian/Ubuntu installation is stale (points to nodes that are not around anymore or haven't upgraded or otherwise unavailable).

I'll try to reproduce the issue and see if I can identify the problem. One way to see if it's a matter of a bad capacity cache is to quit ORC and  `rm -r ~/.config/orc/data`, then start ORC again and wait a few minutes for orcd to learn about the network and try uploading again - but note that doing this will destroy pointers for any objects you've uploaded.

**Comment by bookchin** [comment]
I tried to reproduce on Debian and Windows, but have no issues with uploading/downloading. I did notice something in your original issue above:

> Bundled (.exe/.deb) and v8.7.0 (git HEAD)

We have never done a `8.7.0` release, so I'm wondering if that's a typo or you are running an old version by mistake?

**Comment by bookchin** [comment]
I also noticed after looking at your pastebin logs that a number of the timeouts were from these nodes: https://orc.network/horde/#/parent/xpub6BRiU17o5vnTq8sGX2DgjBoU1ozBZnBDiW4avCwoFUzcYtrHMKxs8BjdS3qt6AAv42KDE2B4D2q3Fj3cYuzuCFoDijnQKJYvoMLJV2rEGVL

These are bootstrap nodes that we run and I just looked at the logs and it appears they got into a weird bad connection state. I kicked them, so maybe try again and see?

**Comment by stoically** [comment]
Can confirm it works now on all platforms (without removing ~/.config/orc/data). :+1: Thanks for the fast fix!

`8.7.0` is the node version for the tests I made with the from source version (referred to as "git HEAD" in that case).

So I guess this is now merely a suggestion for UI improvement. I'll close this - let me know if I should open another Issue or if you want just reopen this one if you want to keep it as reminder.

**Comment by bookchin** [comment]
Good deal. I'd suggest moving the key points for UX over as a comment on #93 so @mrfancymonocle has it on his radar
